### ISSUE TITLE
Import error: No module named 'forward_warp_package'

### ISSUE THREAD

**Issue by mayankamedhe** [zzh-tech/RSCD#2]
Hi!

I am facing the following error while running the training command-

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    trainer.run()
  File "/home/mayanka/RSCD-main/train/trainer.py", line 40, in run
    test(self.para, logger)
  File "/home/mayanka/RSCD-main/train/trainer.py", line 251, in test
    model = Model(para).model.cuda()
  File "/home/mayanka/RSCD-main/model/model.py", line 10, in __init__
    self.module = import_module('model.{}'.format(model_name))
  File "/home/mayanka/anaconda3/envs/rscd/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mayanka/RSCD-main/model/JCD.py", line 4, in <module>
    from forward_warp_package import ForwardWarp
ModuleNotFoundError: No module named 'forward_warp_package'

It will be very helpful if someone can point me towards where to find the "forward_warp_package" package. I was unable to find it in the official python packages list.

**Comment by zzh-tech** [comment]
Please install forward_warp_package package by running install.sh as instructed in the README.md.
